### ISSUE TITLE
XML error : Caravan comp 

### ISSUE THREAD

**Issue by LocoNeko** [LocoNeko/RoadsOfTheRim#3]
More reports of XML errors thrown by the caravan comp. Need to confirm this is the same as issue #1

**Comment by Mehni** [comment]
Related/caused by.

https://github.com/LocoNeko/RoadsOfTheRim/blob/master/Patches/patches.xml#L51 needs to end the xpath with /comps 

Underlying info: The PatchOperationConditional checks if the first xpath is valid. If not, it will execute the <nomatch Classs>. If it is valid, it will execute the <match Class> part. If it's valid, you'll want to add it to the already existing /comps node -- the current xpath of yours adds `<li>` to the root node, which indeed throws errors.

**Comment by LocoNeko** [comment]
Thanks. I will try to understand and fix this asap. Problem is I don't get the errors myself, I guess because I don't have a mod with a caravan comp already. I'll install yours and try to fix this in the next few hours.
Thanks for your patience.
